language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rspec_3_7.gemfile
  - gemfiles/rspec_3_8.gemfile
before_script:
  - cd example && bundle install --quiet && cd ..
script:
  - bundle exec rspec
